/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.awesomequestionnaires;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void ensureMainIsCalledSuccessfully() {
        assertDoesNotThrow(() -> Main.main(new String[0]));
    }
}
