/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.awesomequestionnaires;

import br.com.awesomequestionnaires.CLI.MainMenu;

public class Main {
    public static void main(String[] args) {
        MainMenu menu = new MainMenu();
        menu.boot();
    }
}
