/*
 * This source file was generated by the Gradle 'init' task
 */
package br.com.awesomequestionnaires;

import java.io.IOException;
import java.util.Scanner;

import br.com.awesomequestionnaires.CLI.MainMenu;

public class Main {
    public static void main(String[] args) throws IOException {
        Scanner scanner = new Scanner(System.in);
        MainMenu menu = new MainMenu(scanner);
        menu.boot();
        scanner.close();
    }
}
